AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "This is an AWS Lambda function that collects CloudWatch logs and sends them to HyperDX in bulk, over HTTP."
Parameters:
  hyperdxIngestionKey:
    Type: "String"
    Description: "HyperDX Ingestion API Key."
  hyperdxServiceName:
    Type: "String"
    Description: "The log type you'll use with this Lambda. Please note that you should create a new Lambda for each log type you use. This can be a built-in log type, or your custom log type"
    Default: "hyperdx_cloudwatch_lambda"
  hyperdxFormat:
    Type: "String"
    Description: "JSON or text. If json, the lambda function will attempt to parse the message field as JSON and populate the event data with the parsed fields."
    Default: "text"
    AllowedValues:
      - "text"
      - "json"
  hyperdxEnrich:
    Type: "String"
    Description: "Enriches the CloudWatch events with custom properties at ship time. The format is `key1=value1;key2=value2`. By default is empty."
    Default: ""
  logGroup:
    Type: "String"
    Description: "CloudWatch Log Group name from where you want to send logs."
    Default: ""
  requestTimeout:
    Type: "Number"
    Description: "Timeout in seconds for each http request for sending logs into HyperDX."
    MinValue: 0
    Default: 15
Outputs:
  HyperDXCloudwatchLogsLambda:
    Description: "HyperDX CW logs lambda ARN"
    Value: !GetAtt HyperDXCloudwatchLogsLambda.Arn
Resources:
  HyperDXCloudwatchLogsLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri:
        Bucket: hyperdx-aws-integrations-<<REGION>>
        Key: cloudwatch-auto-deployment/<<VERSION>>/hyperdx-cloudwatch-log-shipper.zip
      FunctionName: !Ref AWS::StackName
      MemorySize: 512
      Timeout: 60
      Events:
        LOsubscription0:
          Type: CloudWatchLogs
          Properties:
            LogGroupName: !Ref logGroup
            FilterPattern: "" #Match everything
      Environment:
        Variables:
          TOKEN: !Ref hyperdxIngestionKey
          TYPE: !Ref hyperdxServiceName
          FORMAT: !Ref hyperdxFormat
          ENRICH: !Ref hyperdxEnrich
          REQUEST_TIMEOUT: !Ref requestTimeout
